##
## vtn.ini 配置文件.
## 提示: ";" 和 "#" 开头的行是注释行.
## 通常下面的默认配置无需修改, 如有特殊需求可在技术支持的指导下酌情修改.
## 配置项前面请勿加空格或TAB等缩进符号.
##
## 提示: "res/cae_xx/cae_init_param.ini" 和 "res/ivw_xx/ivw_g.cfg" 等其他配置文件是vtn内部模块依赖的模板配置(运行时会被 vtn 载入并动态修改), 请勿自行修改(否则会导致运行崩溃). 
##      开发者仅仅可在此文件(vtn.ini)做有限配置.
##

; [VTN引擎] 配置节点
[vtn]
;  工作目录, 默认是: "./"
;  "vtn_api_init" 初始化中若提供了 "work_dir" 则这里配置的会被覆盖. 也就是这里也可以通过初始化接口动态配置.
; work_dir = ./

;  log保存目录, 默认是: "${work_dir}/bin/output". 
;    deprecated: 旧的配置项 "log_audio_dir" 已废弃, 请使用 "log_dir". 
; log_dir = ./bin/output/

;  日志输出等级, 默认为1. LEVEL: 0=off, 1=verbose, 2=debug, 3=info, 4=warning, 5=error
; log_level = 1

;  日志输出通道, 默认输出到 console (在android中默认输出是logcat).
;     ANDROID(LOGCAT) = 2, CONSOLE = 4, FILE = 8.
;   example:  6 = (2 | 4);  <-- log to android(logcat) and console.
;   example: 10 = (2 | 8);  <-- log to android(logcat) and file.
;   example: 12 = (4 | 8);  <-- log to console and file.
;   example: 14 = (2 | 4 | 8);  <-- log to android(logcat), console and file.
;  注意: 若配置了 FILE 输出, 日志会输出到 "${log_dir}" 目录下.
; log_target = 6

;  保存中间音频, 默认为0, 即什么都不存. 
;  如果配了非0值, 我们将保存中间音频到 "${log_dir}".
;    1:原始音频, 2:前端debug中间音频, 4:前端输出; 
;  example: 7 = (1 | 2 | 4), 6 = (2 | 4)
;  注意: 该配置仅供开发调试使用, 且会影响运行效率, 不建议在生产环境开启, 也不会自动清理.
; log_audio = 6

;  输入音频的采样点大小, 支持的是小端 "short/int/float", 默认是 "short".
; input_type = int

;   引擎功能, 默认为 1. 若配为0, 则不会抛出免唤醒方案音频(前1.5s)及唤醒词段音频.
;   bit: output_wakeup_segment = 1
; ability = 0

;  资源标识符. 通常是唤醒资源文件夹名称. 有兴趣了解引擎资源查找规则的可以参见 readme.md 中的说明.
;  "vtn_api_init" 初始化中若提供了 "res_identifier" 则这里配置的会被覆盖.
res_identifier = xfxf


; [授权] 配置节点
[auth]
;   你的应用appid. 可以从aiui网站申请. "vtn_api_init" 初始化中若提供了 "appid" 则这里配置的会被覆盖.
; appid = abcd1234
;   离线授权证书路径, 若配置此项则每次初始化时会优先使用此离线授权文件进行授权验证.
; license = ./res/vtn/device_license.dat


; [前端降噪] 配置节点
[frontend]
;   识别音频 sp_vad 新方案: 0 off, 1 on. 不是所有引擎方案都支持, 这里通常保持默认即可. circle6mic 方案关闭此项则 VAD音频 有抑制效果.
; sp_vad_on = 0
;   波束方案. 不是所有引擎方案都支持, 这里通常保持默认即可. line4mic_std 方案关闭此项则为传统 3波束 方案.
; gevd_on = 0

;  麦克风路数. 通常无需配置. 发版的引擎通常只支持某一种.(也有例外, 例如 "2mic_line4mic_turbo" 支持 2mic/4mic, 这种建议显式配置, 否则走内置默认配置). 
; mic_num = 2
;  参考信号路数. 支持 1 ~ 8. 通常方案默认是2回采, 部分低算力方案及单麦默认是1回采, 可以在这里显式配置覆盖默认值. 
; ref_num = 1
;  麦间距, 单位为毫米. 常规阵列默认是35mm. 不是所有麦间距都支持. 若非35mm间距, 请在配置前找相关人员确认清楚. 
; mic_dist_mm = 17.5
;  oneshot类型: 0: disable, 1: normal oneshot, 4: output audio with wakeup-word.
; oneshot_type = 1

;  回声收敛参数. 常用于改善首次播报造成的自激问题. 若设备在首次交互前播过音(比如引擎启动后播了开机欢迎语), 通常不需要配置.
; aec_coef = ./bin/output/aec_coef

; 以下是 TD 模型配置, 通常无需配置, 保持默认即可. 支持仅配置 td_mvdr / td_dynamic. 
; td_on = 1
; td_type = cldnn
; td_delay = 5
; td_mvdr = 1
; td_dynamic = 0
; td_model = ./res/cae_line4mic_std/mlp_td_cldnn_arm_hxxj_20231013_d5d0.bin
; nr_on = 0


; [后端唤醒] 配置节点
[backend]
;  唤醒模块开关, 默认为1, 即启用.
; on = 0

; 唤醒实例数量, 默认根据前后端特点自动配置. 请勿自行修改, 否则可能崩溃.
; inst_num = 1

;  波束 PK 策略, 默认根据引擎特点自动配置. 支持的有: 1: power; 2: score; 3: power/score.
; pk_strategy = 3

;  闭环优化收集功能, 默认为0. 通常无需配置, 若有额外需求请联系技术支持确认.
;  other options: 1: logpcm. 2: real wake. 3: logpcm + real wake
; closed_loop_mode = 3


; [唤醒词打分] 配置节点
[word_evaluator]
;  唤醒词打分组件模型, 若配置 "model = null", 则不加载模型, 即不启用此功能.
; model = ./res/wake_word_evaluate/wakeup_word_score.bin

