[cae]
#麦克数 1
nMicNum = 1

#参考数，可选值：1 2
nRefNum = 1

#输出通道数
nOutNum = 1

nDerType = 3

#输出采样率，默认16000
nOutSampleRate = 16000

[delay]
#delay开关
delay_on = false

[aec]
#aec开关
aec_on = true

#aec调试选项
aec_debug = false

#aec消除等级，可选值：1-5
aec_level = 5

#aec fft长度，可选值：512 1024
aec_fft_size = 512

#参数文件路径
aec_coef = 

[der]
#der开关
der_on = true

#der调试选项
der_debug = false

#der 阶数，可选值10-24（偶数）
nOrder = 20

[post]
#der开关
post_on = true

#mab调试选项
post_debug = false

[agc]
#agc开关
agc_on = true

#agc调试选项
#agc_debug = false

[mlp]
#NN AES开关
aes_on = true

#NN AES调试选项
aes_debug = false

aes_model = ./asset/mlp_aes_1024_tv.bin

nr_on = true
nr_model = ./asset/mlp_nr_com_20210414.bin

td_on = true
#td_type_config
td_model_type = cldnn
td_delay = 5
td_mvdr_on = false
td_dynamic = false
td_model = ./asset/mlp_td_cldnn_arm_xtxt_20240407_d5d0.bin
